version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: social-network
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080

  redis:
    image: redis:6-alpine
