version: "3.7"
services:
  tests-unit:
    image: golang:1.17-alpine
    working_dir: /app
    command: [ "go", "test", "-v", "./..." ]
    volumes:
      - "./:/app"

  tests-e2e:
    image: golang:1.17-alpine
    working_dir: /app
    command: [ "go", "test", "-v", "./tests/..." ]
    env_file:
      - .env
    volumes:
      - "./:/app"