version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/bin/social-network", "migrate"]
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
#    ports:
#      - "8000:8000"


  mysql:
    image: mysql:8
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
  redis:
    env_file:
      - .env
    image: redis:6-alpine
    ports:
      - "6379:6379"
