version: "3.7"
services:
  tests-unit:
    build:
      context: .
    command: [ "go", "test", "-v", "./..." ]
    volumes:
      - "./:/app"

  tests-e2e:
    build:
      context: .
    command: [ "go", "test", "-v", "./tests/..." ]
    env_file:
      - .env
    volumes:
      - "./:/app"