version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
  redis:
    env_file:
      - .env
    image: redis:6-alpine
