version: "3.7"
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile

  tests-unit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: [ "go", "test", "-v", "./..." ]
    volumes:
      - "./:/app"

  tests-e2e:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: [ "go", "test", "-v", "./tests/..." ]
    volumes:
      - "./:/app"