// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package endpoints

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	services "social-network/pkg/users/services"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9af65625DecodeSocialNetworkPkgUsersEndpoints(in *jlexer.Lexer, out *PostLoginResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Token":
			out.Token = services.SessionId(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9af65625EncodeSocialNetworkPkgUsersEndpoints(out *jwriter.Writer, in PostLoginResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Token\":"
		out.RawString(prefix[1:])
		out.String(string(in.Token))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostLoginResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9af65625EncodeSocialNetworkPkgUsersEndpoints(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostLoginResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9af65625EncodeSocialNetworkPkgUsersEndpoints(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostLoginResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9af65625DecodeSocialNetworkPkgUsersEndpoints(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostLoginResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9af65625DecodeSocialNetworkPkgUsersEndpoints(l, v)
}
func easyjson9af65625DecodeSocialNetworkPkgUsersEndpoints1(in *jlexer.Lexer, out *PostLoginRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email":
			out.Email = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9af65625EncodeSocialNetworkPkgUsersEndpoints1(out *jwriter.Writer, in PostLoginRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostLoginRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9af65625EncodeSocialNetworkPkgUsersEndpoints1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostLoginRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9af65625EncodeSocialNetworkPkgUsersEndpoints1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostLoginRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9af65625DecodeSocialNetworkPkgUsersEndpoints1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostLoginRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9af65625DecodeSocialNetworkPkgUsersEndpoints1(l, v)
}
