name: Tests
on:
  push:
    branches:
      - main
      - deploy
jobs:
  publish-fronted:
    name: tests:backend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DIGITALOCEAN_REGISTRY_URL }}
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.REGISTRY_NAME }}/social-network/frontend-app:${{ env.GITHUB_REF_NAME }}
      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.REGISTRY_NAME }}/social-network/api-app:${{ env.GITHUB_REF_NAME }}

