name: Publish docker image
on:
  workflow_call:
    secrets:
      access_token:
        required: true

env:
  DOCKER_REGISTRY_URL: registry.digitalocean.com
  DOCKER_REGISTRY_NAME: registry.digitalocean.com/rototot
  DOCKER_PROJECT: "social-network"
  DOCKER_APP_NAME_FRONTEND: "frontend"
  DOCKER_APP_NAME_API: "api"
  DOCKER_TAG: ${{ github.ref_name }}

jobs:
  publish-fronted:
    name: docker:publish
    runs-on: ubuntu-20.04
    steps:
      - name: Set docker tag as latest for default branch
        run: |
          if [[ '${{ github.ref_name }}' == 'main' ]]; then DOCKER_TAG='latest'; fi 
          echo $DOCKER_TAG
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

      - name: Print docker tag name
        run: echo $DOCKER_TAG

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.access_token }}
          password: ${{ secrets.access_token }}

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKER_REGISTRY_NAME }}/${{ env.DOCKER_PROJECT }}/${{ env.DOCKER_APP_NAME_FRONTEND }}:${{ env.DOCKER_TAG }}

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKER_REGISTRY_NAME }}/${{ env.DOCKER_PROJECT }}/${{ env.DOCKER_APP_NAME_API }}:${{ env.DOCKER_TAG }}

