name: Tests
on:
  - push
jobs:
  tests:
    name: tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: Check build
        run: |
          cd backend
          go mod download
          go generate ./...
          go build -v ./...
      - name: Unit Tests
        run: ./scripts/run-test-units.sh
      - name: E2E Tests
        run: ./scripts/run-test-e2e.sh


