name: Tests
on:
  - push
jobs:
  tests:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check build
        run: go build -v ./...
      - name: Unit Tests
        run: go test -v ./...


