name: Main Branch Flow
on:
  push:
    branches:
      - main
      - deploy


jobs:
  tests:
    uses: ./.github/workflows/job-tests.yaml

  image-publish:
    uses: ./.github/workflows/job-docker-build-and-publish.yaml
    with:
      access_token: ${{ secrets.DOCKER_ACCESS_TOKEN }}
