name: Main Branch Flow
on:
  push:
    branches:
      - main
      - deploy


jobs:
#  tests:
#    uses: ./.github/workflows/job-tests.yaml

  image-publish:
    uses: ./.github/workflows/job-docker-build-and-publish.yaml
    secrets:
      access_token: ${{ secrets.DOCKER_ACCESS_TOKEN }}
#    needs:
#      - tests
  deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
      - uses: azure/setup-kubectl@v2.0
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: |
          doctl kubernetes cluster kubeconfig save a9aa5e9b-020b-49b1-adae-fe1cfcc61f2c
          helm upgrade --install --wait api ./.helm/backend \
            --set image.tag=latest
    needs:
      - image-publish